language: go

sudo: required
dist: trusty

go:
  - 1.8

os:
  - linux

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go build

script:
  - go test -cover -v $(go list ./... | grep -v vendor/)
